### ISSUE TITLE
A chapter about debugging

### ISSUE THREAD

**Issue by ineiti** [gaehlerm/SoftwareEngineering#6]
I think Debugging should be its own chapter. Most people don't know how to debug. And it's not only about how to use a debugger, but more:

- how to detect a bug (is it a bug or is it a feature?)
- how to reproduce a bug (if you have user input, this one is very difficult. Also for distributed systems, this is one of the worst parts)
- how to isolate a bug (finding the place that is actually wrong)
- how to fix a bug (is it just a simple off-by-one? are two components expecting different data? does something need to be refactored?)

**Comment by gaehlerm** [comment]
My short opinion is: If the code is well written, it is usually fairly easy to track down a bug and fix it. If it is badly written, I don't know how to track down the bug and thus I can't give any good recommendations... that's why the chapter on bugs is so far fairly short: https://github.com/gaehlerm/SoftwareEngineering?tab=readme-ov-file#18-bugs-errors-exceptions 
I'll think about your suggestions, though at least with the distributed systems I could need some help.

**Comment by ineiti** [comment]
Yes, and if the code is well written, there _are no bugs_. Cough, cough...

**Comment by gaehlerm** [comment]
Well, that's exactly one of the main points in this book: we are humans and we are imperfect. Our code is always buggy. But if the code is well written, the bugs are not that hard to track down because from the behavior of the code you can track down quite easily what is wrong. Trust me, I've been there.
If you always struggle with tracking down your bugs, let me know. I'll have a look at your code.

**Comment by ineiti** [comment]
Here is two projects I'm working on: https://github.com/c4dt/dela and https://github.com/c4dt/d-voting - both many many lines, distributed over multiple nodes, and sometimes misbehaving.

Or my pet project for decentralized systems, using WebRTC for connecting browsers and creating a decentralized system: https://github.com/ineiti/fledger

Or many other projects. I've been there, too, and it's always a mess. And debugging non-trivial bugs is always hard.

Currently we're reworking the network layer, because there is _somewhere_ a locking issue, hard to reproduce, because distributed, but it is there (or so I've been told :)

There is a student project now to rewrite that part...

**Comment by gaehlerm** [comment]
Thanks. At first sight, your code looks pretty good to me. The only thing I don't like are all the comments. Make the function names a little longer and you can remove a lot of comments.
I'm sorry, but I guess I'm no help with finding bugs in distributed systems. As I wrote in the first comment, I would need some help with writing such a chapter. And I'm not even sure if I want such a chapter in my book as it's too advanced and specialized. The book is focussed on "classical" single threaded code as that's what many people already struggle with.

**Comment by ineiti** [comment]
And I forgot another part: bug reports by users, which are yet another level :)

**Comment by gaehlerm** [comment]
I added some text on chapter 18. Though I didn't add anything on distributed systems. Please check.

**Comment by gaehlerm** [comment]
I got one idea regarding your problem: if you work on a distributed system, you should consider logging the data send around. It will still be difficult to find the bug, but at least you have the required data containing the bug.

**Comment by ineiti** [comment]
> I got one idea regarding your problem: if you work on a distributed system, you should consider logging the data sent around. It will still be difficult to find the bug, but at least you have the required data containing the bug.

Yes, we have something like that, but it turned out to be too complicated and too verbose to be really useful. So it's mostly printfs in the console, so you know at least the chronological order of the events.

There is this tool which is supposed to be really useful, but we never got around to contact them and try it out:

https://antithesis.com/blog/is_something_bugging_you/
